included:
  - FourSix Coffee Timer
  - FourSixTests
  - FourSixUITests
   
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - comment_spacing
  - line_length
  - xctfail_message
  - unused_closure_parameter
  - todo
  - cyclomatic_complexity
  - function_parameter_count
  - function_body_length
  
identifier_name:
  excluded:
    - id
    - vc
    - ok
    - UIViewControllerTransitionCoordinatorContext