# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  
  desc "Runs all the tests"
  lane :test do
    scan(scheme: "FourSixTests",
    		 device: "iPhone 12")
  end
  
  desc "Run SwiftLint"
	lane :lint do
		swiftlint(
  		mode: :lint,
  		executable: "Pods/SwiftLint/swiftlint",
  		output_file: "test_output/swiftlint.result.json",
  		config_file: ".swiftlint.yml"
  		ignore_exit_status: true
  	)		 
	end
  
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "FourSix Coffee Timer.xcworkspace", scheme: "FourSixUITests")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
end